### ISSUE TITLE
count the CVE of various docker images based on the Dockerfile

### ISSUE THREAD

**Issue by k3ck3c** [second-reality/reverse-tunnel#1]
Hello

I use trivy to find vulnerabilities in docker images
https://github.com/aquasecurity/trivy

I build the docker image and name it reverse, build another with a slight modification, reversev2, not installing the recommends (we want a SSH server, not all the stuff that may be useful in some cases)

diff Dockerfile Dockerfilev2                                                                                                                   
3c3
< RUN apt update && apt install -y openssh-server
---
> RUN apt update && apt install -y --no-install-recommends openssh-server

and build an alpine based Dockerfile, using the latest Alpine for january 2020 (honestly I have not tried the Alpine based docker image)

FROM alpine:3.11.2
RUN apk add --update openssh

# allow any user to read ssh server key
RUN ssh-keygen -t rsa -P "" -f /etc/ssh/ssh_host_rsa_key && \
    ssh-keygen -t ecdsa -P "" -f /etc/ssh/ssh_host_ecdsa_key && \
    ssh-keygen -t ed25519 -P "" -f /etc/ssh/ssh_host_ed25519_key && \
chmod a+r\
 /etc/ssh/ssh_host_rsa_key\
 /etc/ssh/ssh_host_ecdsa_key\
 /etc/ssh/ssh_host_ed25519_key

# run sshd on port $SSH_PORT, only allowing $AUTHORIZED_USER to connect
# and only authorizing forwarding to $AUTHORIZED_DESTINATIONS
# User running this is the one running the container
ENTRYPOINT /usr/sbin/sshd -p "$SSH_PORT" -D\
# show log of connections on stderr
 -e\
# keep clients alive
 -o ClientAliveInterval=180 -o ClientAliveCountMax=2\
# restrict local tunneling to only some destinations
# This is the heart of security!
 -o PermitOpen="$AUTHORIZED_DESTINATIONS"\
# allow anyone to access forwarded ports and not only localhost
 -o GatewayPorts=yes\
# only allow a specific user to connect (the one running container)
 -o AllowUsers="$AUTHORIZED_USER"\
# prevent execution of any command
 -o ForceCommand="/No/Shell/Available/ONLY_TUNNELING_IS_POSSIBLE"\
# other params (man sshd_config)
 -o UsePAM=no\
 -o PasswordAuthentication=no\
 -o AllowStreamLocalForwarding=no\
 -o AllowAgentForwarding=no\
 -o AllowTcpForwarding=yes\
 -o AuthenticationMethods=publickey\
 -o MaxAuthTries=1\
 -o PermitRootLogin=no\
 -o PermitTunnel=yes\
 -o PrintMotd=no\
 -o PidFile=none\

So I have now 3 docker images, the reference called reverse, the slighly modified reversev2 and the Alpine based called reverse-alpine

docker images | grep reverse                                                                                                                                              
reverse                             latest              df010697d963        7 days ago          171MB
reverse-alpine                      latest              734e94a5b57c        7 days ago          14.9MB
reversev2                           latest              a30baccc3247        11 days ago         147MB

so if I check 

trivy reverse > reverse-vuln | grep Total                                                                                                      
Total: 135 (UNKNOWN: 0, LOW: 25, MEDIUM: 89, HIGH: 19, CRITICAL: 2)

trivy reversev2 > reversev2-vuln | grep Total                                                                                                  
Total: 109 (UNKNOWN: 0, LOW: 20, MEDIUM: 74, HIGH: 13, CRITICAL: 2)

trivy reverse-alpine > reverse-alpine | grep Total                                                                                         
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)

So lowering the attack surface may be a good idea

**Comment by second-reality** [comment]
Hi, and thank you for your feedback.

I will definitely give a try to trivy.
I suppose you arrived there with an article on some website, I will update in comment about what I do.

I have been thinking switching to debian distroless (from Google), to completely solve the issue of security. Only ssh server will be present in container. And I like this minimalism idea (compared to Alpine...).

Thanks!
Pierrick

**Comment by second-reality** [comment]
I switched to a multi stage Dockerfile, and now, container is based on distroless approach. https://github.com/GoogleContainerTools/distroless

See latest commit:  https://github.com/second-reality/reverse-tunnel/commit/3680dc34d69727bad88b3be154a9b3d7862ee8c6

Trivy still reports some issues, that are exactly the one present in base image from Google. 
Total: 17 (UNKNOWN: 0, LOW: 1, MEDIUM: 15, HIGH: 1, CRITICAL: 0)

IMHO, that is pretty secureb (even more than alpine). Final container only has sshd and libraries needed. That way of doing things is notably used in production (by some teams) at Google.
